version: "3.9"
services:
  db:
    image: mysql:8
    container_name: org_health_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tali_talent_org_health_development
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
